trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  sonarqubeServiceConnection: 'diglab-sonar-connection'
  workingDir: $(Build.SourcesDirectory)/src
  projectKey: 'things:management:frontend'

jobs:
  - job: ThingsManagementPortal
    displayName: 'ThingsManagement Portal - sonar'
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 16.14.x'
        inputs:
          versionSpec: 16.14.x

      - task: SonarQubePrepare@5
        inputs:
          scannerMode: 'CLI'
          configMode: 'manual'
          cliprojectKey: $(projectKey)
          cliprojectName: 'Things Management Portal'
          cliSources: $(workingDir)
          SonarQube: $(sonarqubeServiceConnection)
          extraProperties: 'sonar.typescript.lcov.reportPaths=coverage/lcov.info'

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false

      - task: Npm@1
        displayName: 'npm run build'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build-prod'

      - task: Npm@1
        displayName: 'run tests'
        inputs:
          command: 'custom'
          customCommand: 'run test-no-watch'

      - task: SonarQubeAnalyze@5

      - task: SonarQubePublish@5
        inputs:
          pollingTimeoutSec: '300'

      - task: sonar-buildbreaker@8
        inputs:
          SonarQube: $(sonarqubeServiceConnection)

  - job: LeanIXSonarqubeIntegration
    dependsOn: ThingsManagementPortal
    condition: succeeded()
    continueOnError: true
    displayName: 'LeanIX Sonarqube Integration'
    pool: 'AutorizadorBD'
    
    steps:
      - task: LeanIXSonarQube@0
        continueOnError: true
        inputs:
          leanixAuthToken: '$(leanixAuthToken)'
          sonarAuthToken: '$(sonarAuthToken)'
          db_username: 'adminvale'
          db_password: '$(SONARLEAN_DB_PASSWORD)'
          db_host: 'rdb-lix-prd.database.windows.net'
          db_name: 'BDLIX_PRD'
          buildPipelineID: '$(System.DefinitionId)'
          projectName: '$(System.TeamProject)'