trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ThingsManagementPortal
    displayName: 'Build - Things Management - Portal - Prod'
    steps:
      - task: AzureKeyVault@1
        displayName: 'Azure Key Vault: kvTMLocationProd'
        inputs:
          azureSubscription: 'things-management-prod'
          KeyVaultName: kvTMLocationProd
          SecretsFilter: 'usernamePortal, passwordPortal, instrumentationKey, appInsightsApiKey, applicationIdKey, iamClientSecret, iamClientId'

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace tokens in **/environment.prod.ts'
        inputs:
          targetFiles: '**/environment.prod.ts'

      - task: NodeTool@0
        displayName: 'Use Node 16.14.x'
        inputs:
          versionSpec: 16.14.x

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false

      - task: Npm@1
        displayName: 'npm run build'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build-prod'

      - task: ArchiveFiles@2
        displayName: 'Archive dist'
        inputs:
          rootFolderOrFile: dist
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
